### ISSUE TITLE
Changes to backend api

### ISSUE THREAD

**Issue by Jumpy-Squirrel** [eurofurence/reg-registration-form#1]
With the backend api now implemented in go, see https://github.com/Jumpy-Squirrel/rexis-go-attendee, there are some minor changes compared to the currently deployed java prototype.

Api Dtos are now defined as written in https://github.com/Jumpy-Squirrel/rexis-go-attendee/blob/master/api/v1/attendee/api.go

Request Changes:
  * addition of id field that should be missing for a new registration (no actual change to this front end required)
  * addition of optional telegram field, to be filled with "@username", please give the user the option to enter this, it was found very useful especially for staff last year

Response Changes:
  * the success response (201 created) has no body, instead you get the standard REST location header with the resource address in URL form, the last part is the Badge Number we assigned
  * the error response body (sent whenever error details are available, never when you get 201) has changed structure slightly. If present, please display the timestamp and the requestid to the user. This will make it easy to find the error in the logs. 
  * in the error response body, the message field is one of the following literal values, to be translated to a human readable error message:

"attendee.data.invalid" (400) - validation errors occurred during data validation, the details field has a list of English language descriptions of the errors. As this front end does its own validation, this shouldn't actually occur in most normal cases, but it is ok to display the details message to the user. Note, the api has no features to block HTML/JS injection attacks (it's an API), so please quote the details message if displaying it to avoid XSS etc.

"attendee.id.invalid" (400) - this shouldn't occur. It means you sent an id when no value for this field was expected. For new registrations, the only allowed value for the id field is "" or (missing).

"attendee.parse.error" (400) - json parse error occurred

"attendee.id.notfound" (404) - can only happen with updates or GET of existing attendees, never for new registrations.

"attendee.write.error" (500) - error while writing to the database

**Comment by Fenmar** [comment]
I would like to clarify the following details before working on this issue:

- Must the request payload contain an id field with an empty string or null or must the id field be absent completely?
- I assume the new telegram field should be named `telegram` in the request payload?
- Could you provide an example of the 201 response header, including the name of the field with the badge number and an example of what "the last part" refers to in relation to the badge number?
- Could you provide an example of the error response body? I assume it's something like this, but would like to confirm:

```json
{
  "timestamp": 1570281423,
  "requestId": 12345,
  "message": "attendee.data.invalid",
  "details": "This and this is wrong, please fix it."
}
```

**Comment by Jumpy-Squirrel** [comment]
Oops, sorry, completely missed this.

- It is valid to send a request for a new attendee with the id field missing completely, but sending an empty field value is also accepted. The only thing that would lead to a validation error is sending a wrong attendee id (and for a new attendee this means any id value)
- the new field is indeed called "telegram". It is optional (i.e. missing or blank string are ok), but if set, it must start with the @ sign
- the response header is called "Location", and its full value for attendee id 17 would be "/api/rest/v1/attendees/17", hence 17 is the last part of the value of the location header, and thus the assigned badge number (= attendee id)
- let's assume you sent a request with an invalid nickname of "$%&^@!$", chose both "sponsor" and "sponsor2" packages, and sent a birthday of "2004-11-23" (too young to attend), then the response status will be 400 (Bad Request) and the body is as follows (only the timestamp and requestid would change):

```
{
  "timestamp": "2019-11-11T21:07:33+01:00",
  "requestid": "05d067f4",
  "message": "attendee.data.invalid",
  "details": {
    "birthday": [
      "birthday must be no earlier than 1901-01-01 and no later than 2001-08-14"
    ],
    "nickname": [
      "nickname field must contain at least two letters, and contain no more than two non-letters"
    ],
    "packages": [
      "cannot pick both sponsor2 and sponsor - constraint violated"
    ]
  }
}
```

Note: I have pretty printed the response json for readability reasons. The original response is, in fact,

```{"timestamp":"2019-11-11T21:07:33+01:00","requestid":"05d067f4","message":"attendee.data.invalid","details":{"birthday":["birthday must be no earlier than 1901-01-01 and no later than 2001-08-14"],"nickname":["nickname field must contain at least two letters, and contain no more than two non-letters"],"packages":["cannot pick both sponsor2 and sponsor - constraint violated"]}}```

**Comment by Fenmar** [comment]
I added the requested changes. We can close this issue once we validate that they are compatible with the current backend

**Comment by Jumpy-Squirrel** [comment]
Tested with other changes on 2019-12-02.
