### ISSUE TITLE
validation order in submit.js is not ideal

### ISSUE THREAD

**Issue by Jumpy-Squirrel** [eurofurence/reg-registration-form#5]
submit.js checks validity conditions in this order:

- TIMESERVER
- CHECKBOX
- COUNTDOWN
- INVALID

I think it would be better to have

- INVALID
- CHECKBOX
- TIMESERVER
- COUNTDOWN

so invalid field values and unchecked checkbox are reported even before the deadline.

**Comment by Fenmar** [comment]
I changed the order of the validation checks. However, keep in mind that this validation is only performed when the user clicks the submit button. This submit button is disabled until the countdown reaches 0; so there is no feedback about an unchecked checkbox before the deadline.

@Jumpy-Squirrel Is this enough or should we add a message like "You must click the checkbox" even before the user clicks the submit button?

**Comment by Jumpy-Squirrel** [comment]
> 
> 
> I changed the order of the validation checks. However, keep in mind that this validation is only performed when the user clicks the submit button. This submit button is disabled until the countdown reaches 0; so there is no feedback about an unchecked checkbox before the deadline.

Oh. Didn't think about that. Duh, sorry.

> @Jumpy-Squirrel Is this enough or should we add a message like "You must click the checkbox" even before the user clicks the submit button?

I'd say this is enough, as long as the other fields validate before submitting. The checkbox is okay to be validated only at submit time, because it's just one click the user needs to make.

**Comment by Jumpy-Squirrel** [comment]
Tested with other changes on 2019-12-02. The other fields validate ahead of time just fine.
