### ISSUE TITLE
backend needs invisible package "room-none" that is always included on new regs

### ISSUE THREAD

**Issue by Jumpy-Squirrel** [eurofurence/reg-registration-form#6]
This is so the room group system gets properly initialized and does not prevent the new registration from being saved. Sorry, forgot to mention this completely.

As a work around I was able to set the config to

```
   "packages": [
     {
+      "code": "attendance,room-none",
+      "default": true,
+      "price": ["90€", "100€", "125€"],
+      "en": {
+        "label": "Entrance Fee (Convention Ticket)",
+        "description": "Basic entrance fee!"
+      },
+      "de": {
+        "label": "Convention Ticket",
+        "description": "Die Basis-Eingangskarte!"
+      }
+    },
```

Note the "code" field. But I think this would be better implemented as an invisible package that is always set by default on new registrations.

I wouldn't really like to implement this change in the backend because there are situations where an admin will later change this package through the same backend rest api, e.g. for guests, so this is an implementation step in the wrong direction.

This is low priority because the above workaround, while not pretty, will also work just fine.

**Comment by Fenmar** [comment]
For the first iteration, I'll hard-code this `room-none` package so that it is always included. In a potential future version we can think of an additional package property `invisible`. Let me know if you see any problems with this approach.

**Comment by Fenmar** [comment]
@Jumpy-Squirrel I added the requested change. Could you verify that it works together with the backend?

**Comment by Jumpy-Squirrel** [comment]
Tested with other changes on 2019-12-02. Works.
