### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by Zefiro** [eurofurence/reg-registration-form#7]
When registering with the exact same data twice, this fails with a non-descriptive technical error displayed:
```
{
  "timestamp": "2019-11-30T02:38:23+01:00",
  "requestid": "bac6a355",
  "message": "attendee.write.error",
  "details": {}
}
```

This error message should clearly indicate what the error was and what the user can do to get a successful registration. This might be something like "This RL name is already registered. Please ensure it is typed correctly. If you already tried to register, please check your spam folder for a confirmation mail"

Having clear, understandable and actionable error messages will reduce both frustration for our attendees as well as support effort from our side.

PS: I've not checked what exactly causes this error, though I suspect some combination of duplicate fields. Please do validate what fields actually must not be duplicate - most fields should allow this. Perhaps a combination of First Name + Last Name + Birthdate, or a combination of Nick + Email. For most other variants I can imagine valid use-cases, incl. duplicate email.

**Comment by Zefiro** [comment]
This is an issue both for the backend (return 4xx e.g 422 instead of 500, and a clear indication what was wrong instead of just "attendee.write.error / no details") and for the frontend (parse the error from the backend and display it in an user-friendly way, if possible)

**Comment by Jumpy-Squirrel** [comment]
Fixed. Backend now correctly returns a 400 status, and the message is very descriptive. The error display isn't exactly pretty when it happens, but together with the measures introduced to prevent sending the duplicate in the first place, I think it's ok. Closing.
