### ISSUE TITLE
Clear the input form after registration

### ISSUE THREAD

**Issue by Zefiro** [eurofurence/reg-registration-form#8]
After a registration, the button will be disabled, but all the data is kept. If a second person wants to register on the same machine, they have to a) manually navigate backwards to the start again and also b) be aware that all entries from the previous registration are kept, which might be surprising (e.g. TShirt Size, Sponsor selection)

Suggestion:
a) after successful registration, the data is cleared locally
and
b) after registration, offer a button labelled "Create another registration", which starts of with a clear form

Note: keeping all data locally even after successful registration (and even after closing the browser and deleting the local cache) might be a GDPR violation.

**Comment by Fenmar** [comment]
Good suggestion! I think rather than clearing the data immediately after successful registration, we should store that the registration was successful, which reg-number was created, and prevent the user from changing the entered data or submitting the same data again. That, together with the "Create another registration" button should provide a clear flow for that use-case.

I think we should not discuss GDPR in this ticket. Feel free to create a new issue if you think this might be a problem.

**Comment by Fenmar** [comment]
Okay, I built something. Here is how it works:

After the user successfully submits their registration, we disable the submit button (like before) and show a button to create another registration. This button takes them to the empty form page. If the user instead refreshes the page, they see the submit page with their data again, but all elements related to changing (the Edit Registration link) or submitting the registration (the TOS checkbox, the countdown and the submit button) are removed. They can still see the data they registered with and see their reg number as well as the hint that it might take some time for the email to arrive. They can also click the "Create new Registration" button to get to a clear reg form.

If the user uses a new tab to start a new registration, we also clear the form.

If the user submits the registration and then uses the back button of the browser to get back to the form field, some browsers automatically fill in the form even though we clear it. If the user clicks "See Summary" in this case, they will see an empty summary and will be unable to submit the reg. If the user changes some input field, it is treated as though they have entered new data for their new registration.

What do you think? Feel free to play around with it and let me know if something does not work.

**Comment by Jumpy-Squirrel** [comment]
I like the new solution with the separate button. Closing this.

**Comment by Jumpy-Squirrel** [comment]
Small addendum: 
our GDPR officer says: "Nope :smile_cat: der local store gehört ja dem Eigentümer der Daten" - meaning leaving data in the local store can not lead to a GDPR violation.
